### PR TITLE
fix(patch): [sc-35212] fix build regression

### LINKED ISSUE #369: Benchmark plugin fails to build on Swift 6.1
`swift package benchmark` fails to build with Swift 6.1 since v1.36.1:

```
$ swift package benchmark
[10/10] Linking BenchmarkBoilerplateGenerator-toolerror: build planning stopped due to build-tool plugin failures
```

The verbose output shows a little more:

```
$ swift package --verbose benchmark
/Users/georgebarnett/workspace/github.com/apple/swift-nio/Benchmarks/.build/checkouts/package-benchmark/Plugins/BenchmarkPlugin/BenchmarkSupportPlugin.swift:21:22: error: 'directoryURL' is unavailable
19 |         // starting with the 6.x tools-version; older toolchains only have `Path`.
20 |         #if compiler(>=6.1)       
21 |         guard target.directoryURL.deletingLastPathComponent().lastPathComponent == "Benchmarks" else { return [] }
   |                      `- error: 'directoryURL' is unavailable                                                                            
22 | 
23 |         let swiftFile = context.pluginWorkDirectoryURL.appending(path: "__BenchmarkBoilerplate.swift")

PackagePlugin.SwiftSourceModuleTarget.directoryURL:3:14: note: 'directoryURL' was introduced in PackageDescription 6.0                                                                                                                                                                    
1 | struct SwiftSourceModuleTarget {
2 | @available(_PackageDescription 6.0)
3 |   public let directoryURL: URL}               
  |              `- note: 'directoryURL' was introduced in PackageDescription 6.0                                                                                                                                                                                                         
4 |                                                             
                                                                      
/Users/georgebarnett/workspace/github.com/apple/swift-nio/Benchmarks/.build/checkouts/package-benchmark/Plugins/BenchmarkPlugin/BenchmarkSupportPlugin.swift:23:33: error: 'pluginWorkDirectoryURL' is unavailable
21 |         guard target.directoryURL.deletingLastPathComponent().lastPathComponent == "Benchmarks" else { return [] }                                                                                                                                                                   
22 |              
23 |         let swiftFile = context.pluginWorkDirectoryURL.appending(path: "__BenchmarkBoilerplate.swift")
   |                                 `- error: 'pluginWorkDirectoryURL' is unavailable                                                                                                                                                                                                    
24 |         let inputFiles = target.sourceFiles.filter { $0.url.pathExtension == "swift" }.map(\.url)                                                                                                                                                                                    
25 |         let outputFiles: [URL] = [swiftFile]

(etc. etc.)
```

### PR DESCRIPTION
**Pull request by supersonicbyte**
## Description

Fixes: https://github.com/ordo-one/benchmark/issues/369

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. 

## Minimal checklist:

- [ ] I have performed a self-review of my own code 
- [ ] I have added `DocC` code-level documentation for any public interfaces exported by the package
- [ ] I have added unit and/or integration tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by hassila — APPROVED** [review]

**Comment by hassila** [comment]
@supersonicbyte can you check why it wasn't caught by CI, maybe need to ask @freef4ll for some help sorting that so we build with 6.1 too...

**Comment by supersonicbyte** [comment]
> @supersonicbyte can you check why it wasn't caught by CI, maybe need to ask @freef4ll for some help sorting that so we build with 6.1 too...

Seems we need to add 6.0 and 6.1 to the matrix
